config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, :only => [:show], as: :user_profile
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "site#index"
  get "/events/search_results", to: "events#search_results"
  get "/events/filter_search", to: "events#filter_search"
  get "/info/about", to: "info#about", :as => :about
  get "/info/contact", to: "info#contact", :as => :contact
  post "/events/:id/like", to: "events#like", :as => :like
  post "/events/:id/unlike", to: "events#unlike", :as => :unlike
  resources :events do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  acts_as_votable
  has_attached_file :poster, styles: { medium: "550x300", thumb: "300x200" }
  validates_attachment_content_type :poster, content_type: /\Aimage\/.*\Z/
  has_many :comments
  belongs_to :user

  # validates_attachment_file_name :poster, matches: [/png\Z/, /jpe?g\Z/]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { medium: "300x300", thumb: "100x100" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  validates_attachment_file_name :avatar, matches: [/png\Z/, /jpe?g\Z/]
  has_many :events
end

app/controllers/application_controller.rb
require 'google_maps_service'
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :setup_extra_device_fields, if: :devise_controller?

  def setup_extra_device_fields
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :password, :password_confirmation, :avatar, :avatar_cache])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :email, :password, :password_confirmation, :avatar, :avatar_cache])
  end
  # Setup global parameters
      GoogleMapsService.configure do |config|
        config.key = 'AIzaSyAWpJMCutqieXGQo5WyxIyKIFVwzMwbFtA'
        config.retry_timeout = 20
        config.queries_per_second = 10
      end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
       @event = Event.find(params[:event_id])
       @a_comment = @event.comments.new(comment_params)
       if @a_comment.save
           redirect_to "/events/#{params[:event_id]}"
       else
           render "show"
       end
   end

   private

   def comment_params
       params.require(:comment).permit(:email, :feedback, :id)
   end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController


  def like
    @event = Event.find(params[:id])
    puts @event.id
    id = params[:id]
    session[:events] ||= {}
    unless session[:events][id]
      puts "adding the vote"
      @event.votes += 1
      @event.save
      session[:events][id] = "yes"
    end
    puts "redirecting"
    redirect_to events_path
  end


  def unlike
    @event = Event.find(params[:id])
    id = params[:id]
    session[:events] ||= {}
    unless session[:events][id]
      @event.votes -= 1
      @event.save
      session[:events][id] = "yes"
    end
    redirect_to events_path
  end

  def index
    @events = Event.order(date: :asc)
    render :index
  end



  def filter_search
  @events = Event.all
    if params[:city].present?
      @events = @events.where(city: params[:city])
  end
     if params[:category].present?
        @events = @events.where(category: params[:category])
    end

      if params[:event_type].present?
        @events = @events.where(event_type: params[:event_type])
    end

      if params[:cost].present?
        @events = @events.where(cost: params[:cost])
    end

    if params[:date].present?
      @events = @events.where(date: params[:date])
  end
    render :filter_search
end

  def search_results
		search_date = params[:date]
    converted_date = search_date.to_date
    search_location =  params[:city]
	  @results = Event.where(city: search_location)
    .where(date: converted_date.beginning_of_day..converted_date.end_of_day)
		render :search_results
	end

  def show
    @event = Event.find params[:id]
    @a_comment = Comment.new
    @comments = @event.comments
    render :show
end

  def new
    authenticate_user!
    @user = current_user
    @event = Event.new
    render :new
  end

def create
  @event = current_user.events.new(event_params)
  @event.save
  redirect_to "/events"
end

  def edit
    @events = Event.where(user_id: current_user.id)
    @event = Event.find(params[:id])
    render :edit
      # else
    # redirect_to "/"

  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to events_path(@event)
    else
      render :edit
    end
  end

    def destroy
        event = Event.find(params[:id])
        event.destroy
        redirect_to  events_path(event)
    end


  private

  def event_params
       params.require(:event).permit(:title, :city, :location, :description, :date, :price, :poster, :event_link)
   end

 end

app/controllers/info_controller.rb
class InfoController < ApplicationController

  def about
    render :about
  end

  def contact
    render :contact
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    render :index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
      @user = User.find(params[:id])
      @events_list = @user.events
      render :show
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<div class="row browse-events">
    <div class="container-fluid">
        <div class="col-md-4 left-top-menu">
            <%= link_to "Home", root_path %>
            <%= link_to "Browse Events", events_path %>
        </div>
        <div class="col-md-4 text-xs-center" id="logo">
            <%= link_to "Eventful", root_path %>
        </div>
        <div class="col-md-4 right-top-menu text-md-right">
            <%= link_to "Create Event", new_event_path %>

            <% if user_signed_in? %>
            <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
            <% if current_user.avatar.exists? %>
            <%= link_to (image_tag current_user.avatar.url(:thumb), class:"img-fluid rounded profile-pic" ), user_profile_path(current_user.id) %>
            <% end %>

        <% else %>
            <%= link_to "Sign Up", new_user_registration_path %>
            <%= link_to "Log In", new_user_session_path %>
            <% end %>
        </div>
    </div>
</div>

<div class="row info-bar">
    <div class="container">
        <span>Edit your event</span>
    </div>
</div>

<%= render "partials/create_event_form" %>

app/views/events/filter_search.html.erb
<!-- Results for filters -->
    <!-- <div class="row other-events">
      <div class="container-fluid">
        <div class="col-md-4 left-top-menu">
            <%= link_to "Home", root_path %>
              <%= link_to "Browse Events", events_path %>

        </div>
        <div class="col-md-4 text-xs-center" id="logo"> <%= link_to "Eventful", root_path %></div>
        <div class="col-md-4 right-top-menu text-md-right">
          <%= link_to "Create Event", new_event_path %>
          <%= link_to "Sign Up", new_user_registration_path %>
          <%= link_to "Log In", new_user_session_path %>
        </div>
    </div>
    </div>

    <div class="row info-bar">
    <div class="container">
      <span>Events results for your search</span>
    </div>
    </div> -->

<!-- <% @events.each do |event| %>
 <p>
  <%= event.city %><%= event.title %>
 </p>
<% end %> -->
<!--
<div class="row event-listing">
  <% @events.each do |event| %>
        <div class="col-sm-12">
          <p><%= link_to "#{event.title}", event_path(event.id) %></p>
        </div>
  <% end %>
</div> -->



<div class="row filter-results">
    <div class="container-fluid">
        <div class="col-md-4 left-top-menu">
            <%= link_to "Home", root_path %>
            <%= link_to "Browse Events", events_path %>
        </div>
        <div class="col-md-4 text-xs-center" id="logo">
            <%= link_to "Eventful", root_path %>
        </div>
        <div class="col-md-4 right-top-menu text-md-right">
            <%= link_to "Create Event", new_event_path %>

            <% if user_signed_in? %>
            <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
            <% if current_user.avatar.exists? %>
            <%= link_to (image_tag current_user.avatar.url(:thumb), class:"img-fluid rounded profile-pic" ), user_profile_path(current_user.id) %>
            <% end %>

        <% else %>
            <%= link_to "Sign Up", new_user_registration_path %>
            <%= link_to "Log In", new_user_session_path %>
            <% end %>
        </div>
    </div>
</div>

<div class="row info-bar">
    <div class="container">
        <span>Events results for you</span>
    </div>
</div>
<div class="container featured-events-body">
    <div class="col-sm-8 featured-events-list">
        <div class="row">
          <% @events.each do |event| %>
          <div class="row event-listing">
            <div class="col-sm-4 text-sm-right">
                <%= link_to (image_tag (event.poster.url(:medium)), class: "img-fluid"), event_path(event.id) %>
                <div class="row votes">
                  <%= link_to (image_tag ("like.svg"), class: "col-md-3 offset-md-2 img-fluid"), like_path(event.id), :method => :post %>
                  <%= link_to (image_tag ("unlike.svg"), class: "col-md-3 offset-md-2 img-fluid"), unlike_path(event.id), :method => :post %>

                </div>
                <p><%= event.votes %></p>

            </div>

              <div class="col-sm-8 text-sm-center">
                  <p><%= link_to "#{event.title}", event_path(event.id), class: "detail-link"%></p>
              </div>

              <div>
                  <p><%= event.date.strftime("%A, %d %b %Y") %></p>
              </div>


              <div>
                  <p>City:<%= event.city %></p>
              </div>
              <div>
                  <p>Location:<%= event.location %></p>
              </div>
          </div>
          <% end %>
        </div>
    </div>
  </div>

    <%= render "partials/footer" %>


<!-- ------------- -->

app/views/events/index.html.erb
<!-- browse events -->
<div class="row browse-events">
    <div class="container-fluid">
        <div class="col-md-4 left-top-menu">
            <%= link_to "Home", root_path %>
            <%= link_to "Browse Events", events_path %>
        </div>
        <div class="col-md-4 text-xs-center" id="logo">
            <%= link_to "Eventful", root_path %>
        </div>
        <div class="col-md-4 right-top-menu text-md-right">
            <%= link_to "Create Event", new_event_path %>

            <% if user_signed_in? %>
            <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
            <% if current_user.avatar.exists? %>
            <%= link_to (image_tag current_user.avatar.url(:thumb), class:"img-fluid rounded profile-pic" ), user_profile_path(current_user.id) %>
            <% end %>

        <% else %>
            <%= link_to "Sign Up", new_user_registration_path %>
            <%= link_to "Log In", new_user_session_path %>
            <% end %>
        </div>
    </div>
</div>

<div class="row info-bar">
    <div class="container">
        <span>Upcoming Events</span>
    </div>
</div>
<div class="container featured-events-body">
    <div class="col-sm-8 featured-events-list">
        <div class="row">
            <%= render "partials/event_listing" %>
        </div>
    </div>

    <div class="col-sm-3 offset-sm-1 events-filters">

        <div class="row text-sm-center">
            Search for more events:
        </div>

        <div class="row">
            <div class="row filters">
                <%= render "partials/filter_search_forms"%>
            </div>
        </div>
    </div>


  </div>

    <%= render "partials/footer" %>

app/views/events/new.html.erb
<!-- create events -->

<div class="row event-create">
    <div class="container-fluid">
        <div class="col-md-4 left-top-menu">
            <%= link_to "Home", root_path %>
            <%= link_to "Browse Events", events_path %>
        </div>
        <div class="col-md-4 text-xs-center" id="logo">
            <%= link_to "Eventful", root_path %></div>
        <div class="col-md-4 right-top-menu text-md-right">
              <%= link_to "Create Event", new_event_path %>
            <%= link_to "Log out", destroy_user_session_path, method: 'delete' %>
            <% if @user.avatar.exists? %>
            <%= image_tag (@user.avatar.url(:thumb)), class: "img-fluid rounded profile-pic" %>
            <% end %>
        </div>
    </div>
</div>

<div class="row info-bar">
  <div class="container">

        <span>Create & share a new event</span>

  </div>
</div>

<div>
    <div class="container">
        <%= render "partials/create_event_form" %>
    </div>
</div>
</div>
</div>

app/views/events/search_results.html.erb
<!-- Search results for landing form
    <div class="row other-events">
      <div class="container-fluid">
        <div class="col-md-4 left-top-menu">
            <%= link_to "Home", root_path %>
            <%= link_to "Browse Events", events_path %>
        </div>
        <div class="col-md-4 text-xs-center" id="logo"> <%= link_to "Eventful", root_path %></div>
        <div class="col-md-4 right-top-menu text-md-right">
          <%= link_to "Create Event", new_event_path %>
          <%= link_to "Sign Up", new_user_registration_path %>
          <%= link_to "Log In", new_user_session_path %>
        </div>
    </div>
    </div>

    <div class="row info-bar">
    <div class="container">
      <span>Events for your dates & city</span>
    </div>
    </div>
<h1> </h1> -->

  <!-- <% @results.each do |event| %>
	 <p>
		<%= event.id %><%= event.location %>
    <%= event.id %><%= event.date %>
	 </p>
  <% end %> -->


  <div class="row landing-results">
      <div class="container-fluid">
          <div class="col-md-4 left-top-menu">
              <%= link_to "Home", root_path %>
              <%= link_to "Browse Events", events_path %>
          </div>
          <div class="col-md-4 text-xs-center" id="logo">
              <%= link_to "Eventful", root_path %>
          </div>
          <div class="col-md-4 right-top-menu text-md-right">
              <%= link_to "Create Event", new_event_path %>

              <% if user_signed_in? %>
              <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
              <% if current_user.avatar.exists? %>
              <%= link_to (image_tag current_user.avatar.url(:thumb), class:"img-fluid rounded profile-pic" ), user_profile_path(current_user.id) %>
              <% end %>

          <% else %>
              <%= link_to "Sign Up", new_user_registration_path %>
              <%= link_to "Log In", new_user_session_path %>
              <% end %>
          </div>
      </div>
  </div>

  <div class="row info-bar">
      <div class="container">
          <span>Events results for you</span>
      </div>
  </div>
  <div class="container featured-events-body">
      <div class="col-sm-8 featured-events-list">
  <div class="row">
    <% @results.each do |event| %>
    <div class="row event-listing">
      <div class="col-sm-4 text-sm-right">
          <%= link_to (image_tag (event.poster.url(:medium)), class: "img-fluid"), event_path(event.id) %>
          <div class="row votes">
            <%= link_to (image_tag ("like.svg"), class: "col-md-3 offset-md-2 img-fluid"), like_path(event.id), :method => :post %>
            <%= link_to (image_tag ("unlike.svg"), class: "col-md-3 offset-md-2 img-fluid"), unlike_path(event.id), :method => :post %>

          </div>
          <p><%= event.votes %></p>

      </div>

        <div class="col-sm-8 text-sm-center">
            <p><%= link_to "#{event.title}", event_path(event.id), class: "detail-link"%></p>
        </div>

        <div>
            <p><%= event.date.strftime("%A, %d %b %Y") %></p>
        </div>


        <div>
            <p>City:<%= event.city %></p>
        </div>
        <div>
            <p>Location:<%= event.location %></p>
        </div>
    </div>
    <% end %>
  </div>
</div>
</div>
<%= render "partials/footer" %>

app/views/events/show.html.erb
<!-- Each Event details -->
<div class="row event-details">
    <div class="container-fluid">
        <div class="col-md-4 left-top-menu">
            <%= link_to "Home", root_path %>
            <%= link_to "Browse Events", events_path %>

        </div>
        <div class="col-md-4 text-xs-center" id="logo">
            <%= link_to "Eventful", root_path %></div>
        <div class="col-md-4 right-top-menu text-md-right">
            <%= link_to "Create Event", new_event_path %>
            <% if user_signed_in? %>
            <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
        <% else %>
            <%= link_to "Sign Up", new_user_registration_path %>
            <%= link_to "Log In", new_user_session_path %>
            <% end %>
        </div>
    </div>
</div>

<div class="row info-bar">
    <div class="container">
        <span>Event details</span>
          <% if user_session && current_user.id == @event.user_id %>
        <%= link_to "Edit", edit_event_path(@event) %>
        <%= link_to "Delete", event_path(@event), method: "delete", data: { confirm: "Are you sure you want to delete this event?" } %>
        <%end%>
    </div>
</div>

<div class="container">
    <div class="row event-title">
        <h1 class="title">
            <%= @event.title %>
        </h1>

    </div>
</div>

<div class="container">
    <div class="col-md-6">

        <!-- <div class="row container"> -->
        <%= image_tag (@event.poster.url(:medium)), class: "img-fluid rounded" %>
        <!-- </div> -->
    </div>

    <div class="col-md-6 detail-info">
        <!-- <div class="row"> -->
        <p>
            City:
            <%= @event.city %>
        </p>
        <p>Location:
            <%= @event.location %>
        </p>
        <p>
            Description:
            <%= @event.description %>
        </p>
        <p>
            Event Link:
            <%=link_to @event.event_link, @event.event_link %>
        </p>
        <p>
            Date:
            <%= @event.date.strftime("%A, %d %b %Y") %>
        </p>
        <p>
            Cost:
            <%= @event.cost %>
        </p>
        <p>
            Price: USD<%= @event.price %>
        </p>
    </div>
</div>

<%= render "partials/maps" %>

    <div class="row">
        <%= render "partials/comments" %>


        <div class="container">

              <h3 class="col-sm-5">Comments</h3>

              <div class="col-sm-7" id="comments">
                  <% @comments.each do |comment| %>
                  <div class="media">
                      <div class="media-body">
                          <h5 class="media-heading"><%= comment.email %></h5>
                          <p><%= comment.feedback %></p>
                          <hr>
                      </div>
                  </div>
                  <% end %>
              </div>
      </div>

    </div>


<%= render "partials/footer" %>


<!-- <%= link_to "Featured Events", events_path %> -->

app/views/info/about.html.erb
<div class="row about-us">
    <div class="container-fluid">
        <div class="col-md-4 left-top-menu">
            <%= link_to "Home", root_path %>
            <%= link_to "Browse Events", events_path %>
        </div>
        <div class="col-md-4 text-xs-center" id="logo">Eventful</div>
        <div class="col-md-4 right-top-menu text-md-right">
            <%= link_to "Create Event", new_event_path %>

            <% if user_signed_in? %>
            <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
            <% if current_user.avatar.exists? %>
            <%= link_to (image_tag current_user.avatar.url(:thumb), class:"img-fluid rounded profile-pic" ), user_profile_path(current_user.id) %>
            <% end %>

        <% else %>
            <%= link_to "Sign Up", new_user_registration_path %>
            <%= link_to "Log In", new_user_session_path %>
            <% end %>

        </div>
    </div>


    <div class="container text-md-center mission">
        <h1>Create | Discover | Connect</h1>
        <p> Eventful is an events platform providing a space for finding and creating events happening in Nicaragua's top tourist destinations.
        We created a simple application that allows anyone to create, share, find and enjoy events happening around them.  Find classes, concerts, festivals, fairs, art expos, parties and more. We provide the space, you fuel it with events, passion and connection. </p>
    </div>
</div>

app/views/info/contact.html.erb
<div class="row" class="contact-us">
    <div class="container-fluid">
        <div class="col-md-4 left-top-menu">
            <%= link_to "Home", root_path %>
            <%= link_to "Browse Events", events_path %>
        </div>
        <div class="col-md-4 text-xs-center" id="logo">Eventful</div>
        <div class="col-md-4 right-top-menu text-md-right">
            <%= link_to "Create Event", new_event_path %>

            <% if user_signed_in? %>
            <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
            <% if current_user.avatar.exists? %>
            <%= link_to (image_tag current_user.avatar.url(:thumb), class:"img-fluid rounded profile-pic" ), user_profile_path(current_user.id) %>
            <% end %>

        <% else %>
            <%= link_to "Sign Up", new_user_registration_path %>
            <%= link_to "Log In", new_user_session_path %>
            <% end %>

        </div>
    </div>

    <div class="container live-enjoy text-md-center">
        <h2>Create | Enjoy | Connect</h2>
        <p>Eventful is an events platform providing a space for finding and creating events happening in Nicaragua's top tourist destinations.
        We created a simple application that allows anyone to create, share, find and enjoy events happening around them.  Find classes, concerts, festivals, fairs, art expos, parties and more. We provide the space, you fuel it with events and passion. </p>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventful</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <%if notice != nil %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>

    
  </body>
</html>

app/views/partials/_comments.html.erb
<div class="container">


<%= form_for [@event, @a_comment] do |f| %>

<div class="form-group comment-area">
  <h3 class="">Share a comment</h3>
    <%= f.label :email, class: "col-sm-2 form-label" %>
    <%= f.text_field :email, class: "form-control" %>

</div>
<div class="form-group">
    <%= f.label :feedback, class: " col-sm-2 form-label"  %>
    <%= f.text_area :feedback, class: "form-control"%>
</div>
<div class="form-group">
    <div class="">
        <%= f.button class: "btn btn-primary"%>
    </div>
</div>
<% end  %>

</div>

app/views/partials/_event_listing.html.erb
<% @events.each do |an_event| %>
<div class="row event-listing">
  <div class="col-sm-4 text-sm-right">
      <%= link_to (image_tag (an_event.poster.url(:medium)), class: "img-fluid"), event_path(an_event.id) %>
      <div class="row votes">
        <%= link_to (image_tag ("like.svg"), class: "col-md-3 offset-md-2 img-fluid"), like_path(an_event.id), :method => :post %>
        <%= link_to (image_tag ("unlike.svg"), class: "col-md-3 offset-md-2 img-fluid"), unlike_path(an_event.id), :method => :post %>

      </div>
      <p><%= an_event.votes %></p>


      <!-- <a href="/events/<%=an_event.id%>/upvote"> <img src="assets/like.svg"> method="post"</a>
      <a href="/events/<%=an_event.id%>/upvote"> <img src="assets/unlike.svg"> </a> -->
  </div>

    <div class="col-sm-8 text-sm-center">
        <p><%= link_to "#{an_event.title}", event_path(an_event.id), class: "detail-link"%></p>
    </div>

    <div>
        <p><%= an_event.date.strftime("%A, %d %b %Y") %></p>
    </div>


    <div>
        <p>City:<%= an_event.city %></p>
    </div>
    <div>
        <p>Location:<%= an_event.location %></p>
    </div>
</div>
<% end %>

app/views/partials/_footer.html.erb
<footer class="">
    <div class="container text-md-center footer-text">
        <%= link_to "About", about_path %>
        <%= link_to "Contact", contact_path %>
    </div>
</footer>

app/views/site/index.html.erb
<!-- Landing page -->
<div class="row" style="background-color: #000;">


<div class="" id="box-wrapper" >
    <div class="container-fluid">
        <div class="col-md-4 left-top-menu">
            <%= link_to "Home", root_path %>
            <%= link_to "Browse Events", events_path %>
        </div>
        <div class="col-md-4 text-xs-center" id="logo">Eventful</div>
        <div class="col-md-4 right-top-menu text-md-right">
            <%= link_to "Create Event", new_event_path %>

            <% if user_signed_in? %>
            <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
            <% if current_user.avatar.exists? %>
            <%= link_to (image_tag current_user.avatar.url(:thumb), class:"img-fluid rounded profile-pic" ), user_profile_path(current_user.id) %>
            <% end %>

        <% else %>
            <%= link_to "Sign Up", new_user_registration_path %>
            <%= link_to "Log In", new_user_session_path %>
            <% end %>

        </div>
    </div>

    <div class="container live-enjoy text-md-center">
        <h2>Create | Discover | Connect</h2>
        <h5>Find & create events that enrich your community</h5>
    </div>

    <div class="row landing-search-form">
        <%= form_tag("/events/search_results", class: "form-inline text-md-center" ,:method => "get") do %>
        <div class="form-group">
            <%= label_tag :date, "When:" %>
            <%= date_field_tag :date, {}, {class: "form-control"} %>
        </div>

        <div class="form-group">
            <%= label_tag(:city, "Where:") %>
            <%= text_field_tag :city, "", placeholder: "Granada, León", class: "form-control" %>
        </div>
        <%= submit_tag "Find Events", :class => "btn btn-primary" %>
        <% end %>

    </div>


</div>

  <%= render "partials/footer" %>

</div>

app/views/users/show.html.erb
<div class="row event-details">
    <div class="container-fluid">
        <div class="col-md-4 left-top-menu">
            <%= link_to "Home", root_path %>
            <%= link_to "Browse Events", events_path %>

        </div>
        <div class="col-md-4 text-xs-center" id="logo">
            <%= link_to "Eventful", root_path %></div>
        <div class="col-md-4 right-top-menu text-md-right">
            <%= link_to "Create Event", new_event_path %>
            <% if user_signed_in? %>
            <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
        <% else %>
            <%= link_to "Sign Up", new_user_registration_path %>
            <%= link_to "Log In", new_user_session_path %>
            <% end %>
        </div>
    </div>
</div>

<div class="row info-bar">
    <div class="container">
        <span><% if user_signed_in? %>
            <div>Welcome,
                <%= current_user.first_name%>!
                <%= link_to "Edit your profile", edit_user_registration_path %></div>
            <% end %></span>
    </div>
</div>

<div class="container">
    <div class="row col-md-6 account-title">
        <h3>
            Your account information</h3>

        <ul class="account-info">
            <li>Your email:
                <%= current_user.email%></li>
            <li>Joined:
                <%= current_user.created_at.strftime("%A, %d %b %Y")%></li>
            <li>Your profile picture:
            </li>
            <li>
                <%= image_tag current_user.avatar.url(:medium)%>
            <li></br>

        </div>
        <div class="row col-md-6 published-title">
            <h3>
                Your published events
            </h3>

            <ul>
                <% @events_list.each do |one_event| %>
                <li>
                    <p><%= link_to "#{one_event.title}", event_path(one_event.id), class: "detail-link"%></p>
                </li>
                <% end %>
            </ul>
    </ul>
</div>
</div>
    <%= render "partials/footer" %>